# name = """ kdgajd09

# jdhdgdhdhdj

# jdjdhdhgdhjdjd

# """
# num = eval(input("enter your name:"))
# print(type(num))
# print(num)
# x = int(input("enter your x:"))
# y = int(input("enter your y:"))
# print(type(x))
# print(x+y)
# a = 20
# b = 30
# if b<a:
#     print(b,"<",a)
# else:
#     print(b,">",a)
# s = "lavanya"
# for char in s:
#     print(char)

# l = [1,2,3,4,5,6,7]
# for even in l:
#     print(even)

# i = 0
# while i<10:
#     i = i+1
#     print(i)

# s  = "learningpythoniseasy"
# for char in s:
#     if char == "is":
#         break
#     print(char)
# for i in range(50,100):
#     if i == 70:
#         print("battery was full")
#         break
#     print(i)
# l = ["praveeen","ram","krishna","shiva","kiran"]
# for name in l:
#     if "k" in name:
# #      pass
# #     print(name)
# name = "praveen lavanya mjuduhfhdgfgh"
# print(name[-1])

# num = "123456789"
# print(num[1:9:2])
# t = [10,20,"teja",99.9,True,10]
# print(type(t))
# print(t)
# num = eval(input("enter your num:"))
# print(type(num))
# print(num)

# x = int(input("enter your x:"))
# y = float(input("enter your y:"))
# print(type(x))
# print(x+y)
# a = 20
# d = 30
# if d>a:
#     print(d,">",a)
# else:
#     print(a,"<",d)

# for i in range (50,100):
#     if i == 60:
#         print("battery is full")
#         break
#     print(i)

# for i in range(10):
    # if i == 6:
    #     break
    # print(i)

# s = "learning python"
# for char in s:
#     if char == " ":
#         break
#     print(char)
# name = ("mamu")
# print(name[2])
# in and not in 
# s = "learning python is very easy"
# print("py" in s)
# print("java" in s)
# print("learning" not in s)

# names = "ram , krishna, laxman , bhrat, shiva"
# str = input("enter your name:")

# if str in names:
#     print(str,"is in", names)
# else:
#     print(str,"not in",names)
# t = "ram krishna shiva venkat"
# s = input("enter your name:")
# if s in t :
#     print(s, "is in ", t)
# else:
#     print(s,"not in",t)

# l = ["ram" ,"laxman","bhrat","shiva"]
# s = input("enter your name:")
# for i in l:
#     if s == i:
#         print(s,"is in",l )
# x = int(input("enter a number:"))
# print()
# if (x % 5 == 0):
#     print("buzz")
# if(x%3 == 0):
#     print("fizz")

# i = 0
# count = 2
# while i < 10:
#     count = count**2
#     i = i+1
#     print(count)
# l = "praveen","lavanya","kiran","seeta"
# s = input("enter your name:")
# # if s in l:
# #     print(s,"is in", l)
# # else:
# #     print(s,"not in",l)
# for i in l:
#     if s == i:
#         print(s,"is in l")
#     else:
#         print("not available")


# s1 = " learning"
# print(s*10)

# print((s+" ")*10)
# print(s1*10)
# s = " learning python is very easy "
# print(len(s))
# ss = s.lstrip()
# print(ss)
# print(len(ss))
# ss = s.rstrip()
# print(ss)
# print(len(ss))

# s1 = "ram"
# s2 = "raju"
# print(s1>s2)
# print(s1<s2)
# print(s1==s2)

# a = "a"
# b = "A"
# print(ord("a"))
# print(ord("A"))
# print(ord("z"))
# print(ord("Z"))
# print(ord("m"))
# print(ord("j"))
# print(a>b)

# s = " i am lavanya i learning python "
# print(len(s))
# ss = s.split(" ")
# print(ss)
# print(s[::-1])

# s = "learning python is easy"
# print(s.count("l"))
# print(s.count("e"))
# print(s.count("a"))
# print(s.count("r"))
# print(s.count("n"))
# print(s.count("i"))
# print(s.count("g"))
# print(s.count("p"))
# print(s.count("y"))
# print(s.count("t"))
# print(s.count("h"))
# print(s.count("o"))
# print(s.count("s"))
# print(s.count(s))

mail = "praveen@gmail.com"
website = "www.skywavesssoftware.com"

# # startswith()
# if website.startswith("https"):
#     print("open website")
# else:
#     print("invalid site")

if mail.endswith("skywavessoftwares.com"):
    print("valid gmail")

else:
    print("invalid gmail")
# ss= s.strip()
# len(ss)
# print(len(ss))

# s = "lavanya123"
# print(type(s))
# print(type(s[-1]))

# s1 = "PRAVEEN"
# print(s1.isupper())
# print(s.isupper())
# s = "learning"
# s1 = "PRAVEEN"
# print(s+s1)
# s1 = "Lavanya Is In Skywaves"
# s1 = " "
# print(s.isdigit())
# print(s1.isdigit())
# names = ["mike","alice","mark"]
# joinednames = '@'.join(names)
# print(joinednames)
# s = "lavanya hema"
# print(s.upper())
# s = "2"
# d = "8"
# print(s+d)
# str = "larning"
# # print(str.count("l"))
# for char in s:
#     if char == "i":
#         print(char)
# x = input("enter a word or sentence:")
# print("uppercase-" ,x.upper())
# x = input("enter a word or sentence:")
# print("split-",x.split("e"))
# s = "iamlavanya"
# print(s.split())
# s = "10,20,30,304,0"
# print(type(s))
# print(type(list(s)))
# l1 =[1,2,3,4]
# l2 = [5,6,7,8]
# l1.extend(l2)
# print(l1)

# for i in range (10):
#     l.append(i)

# l.append(10)
# l.append(11)

# print(l)
# l1 = [20,200]
# l1.extend('true')
# print(l1)

# s = [1,2,3,4,5,6,7,8,9,10]
# for ele in s :
#     rem = ele %2
#     if (rem ==0):
#         print("even")
#         print(ele)


# i =  100
# while i>=5:
#     print("lavu")
#     i = i-1

# print(i)
# i = 100
# while i >= 1:
#     print("hello")
#     i = i -1
# i = 1
# while i<=10:
#     print(5*i)
#     i = i+1

# print(i)
# n = int(input("enter a number:"))
# nums = [1,4,9,16,25,36,49,64,81,100]
# idx = 0
# while idx<len(nums):
#     print(nums[idx])
#     idx=idx +1
# n = int(input("enter a number:"))
# i = 1
# while i<=10:
#     print(n*i)
#     i = i +1


# l1 = [1,2,3,4]
# l2 = [5,6,7,8]
# print(l1>l2)
print("----------------------------------------------")
# l = [2,3,1,5,4,6]
# # print(l.reverse())
# # print(l)
# print(l[::-1])
# name = ["ram","shiva","krish","venkat","kesav"]
# cname = name.copy()
# print(name)
# print(cname)
# print(id(name))
# print(id(cname))
# # dnames = name[:]
# # print(name)
# # print(dnames)
# # print(id(name))
# # print(id(dnames))

# # for i in name:
# #     if "venkat" in i:
# #         name.remove("venkat")

# l = [x for x in range (1,10+1)]
# print(l)

# l = []
# for i in range (10):
#     l.append(i)

# print(l)

# # print(name)
# # x = name
# # print(x)
# # print(id(x))
# t = (1,2,3,4,(5,6,7,8))
# # print(t[4][2])
# print(t[2:4+1])
# t =(1,2,3,4,5,6)
# l = list(t)
# print(l)
# t = (1,2,3,4,5,6,7,8,9)
# t = (x for x in range(1,11))
# print(t)
# print(list(t))
# l = []
# for i in range  (10):
#     l.append(i)

# print(l)

# l.append(10)
# l.append(11)

# print(l)
l = []
for i in range (10):
    l.append(i)

print(l)

l = [0,1,2,3,4,5,6,7,8,9]
z = [10,11,12,13,14,15,16]
l.extend(z)

print(l)
# l.insert(2,20)

# print(l)
l1 = [20,10]
l1.extend('t')
print(l1)

l = ['a','b','c','d','e','f']
print(l[3])
print(l[0:4])

l1 =[1,2,3]
l2 =[4,5,6]
print(l1<l2)

# l = [1,2,3,4,5,6,7,8,9,10]
# print(l.del())
# print(l)
# l = ['a','b','e','h','c','g']
# print(l.sort())
# print(l)
# l . reverse()
# print(l)

# print(l[::-1])
# names = ["ram","krishna","seeta","geeta"]
# # for i in names:
# #     names.remove("ram")

# print(names)
# x = names
# print(x)
# print(id(x))
# print(id(names))

names = ["ram","krishna","seeta","venkat"]
cnames = names.copy()

print(names)
print(cnames)
print(id(names))
print(id(cnames))

l = [i for i in range(1,10+1) if i%2==0]
# print(l)
# l = []
# for i in range (1,10+1):
#     if i%2 == 0:
#         l.append(i)
   
print(l)

t = (True, 10,10.2,"name")
print(t.count(10))

t = (1,2,3,4,(5,6,7))
print(t[4][0])
print(t[2:4+1])
t = (x for x in range (1,11) if x%2==0)
print(t)
print(tuple(t))
s ={2,3,4,"string",99.99,True}
print(s)
print(type(s))
s = set()
l = [1,2,3,4]
s.update(l)
print(s)
s.add(10)
print(s)
s ={0,1,2,3,4,5,6,7,8,9}
s.pop()
print(s)
s.pop()
print(s)
print("----------------------")
s = {0,1,2,3,4,5,6,7,8,9}
s.discard(10)
print(s)
# print("---------------------")
# s.remove(10)
# print(s)
s = {1,2,3,4,5,6,7}
s = type(l)

print(s)
# print(s[1])
# print(s)
# ls = list(s)
# print(ls)
# s1 = {1,2,3,4,5,6,7,8}
# S2 = {9,10,11,12,13,14,15,1,2,3,4}
# print(s1.symmetric_difference(S2))

dict = {}

dict["name"] = "krishna"
print(dict)

dict["age"] = 28
print(dict)

dict["slaary"] = 90000
print(dict)
# dict = {}
# for item in range (5):
    # key = input("enter your key:")
    # value = input("enter your value:")
    # dict[key] = value

# print(dict)
# print(dict)
# dict["name - 2"]  = "teja"
# print(dict)
print("--------------")
print(dict.items())
print(dict)

print(dict.pop("name"))


print(dict)

print("====================================")
# x = {1001 : "a",1002 : "b",1003 : "c"}
# print(x)

# dict.update(x)
# print(dict)

def wish(name):
    print("hi,hello goodmorning",name)

wish("lavanya")
wish("abhi")

def add(x,y):
    return x+y

# print(add(10,30))
sm = add(10,30)
print(sm)

l = [1,2,3,4,5,6,7,8]
for val in l:
    print(val)

t = ("11.30,22,34.8")
l = list(t)
print(l)

t = (1,2,3,4,5)
l = list(t)
print(l)

t = (1,2,3,4,5,6)
l = list(t)
print(l)
l =[1,2,3,4,5,6,7,8,9,10]
# l.insert(2,5.0)
# print(l)
# t = tuple(l)
# print(t)

# t = (x for x in range  (1,11) if x%2==0)
# print(t)
# print(type(t))
# s = set()
# l = [1,2,3,4,5]
# s.update(l)
# print(s)
# s = {1,2,3,4,5,6,7,8}
dict = {}
# dict["name"] = "krishna"
# print(dict)
# for item in range(1):
#     key = input("enter key here:")
#     value = input("enter value here:")
#     dict[key] = value

# print(dict)
dict["name-2"] = "teja"
# print(dict)

print(dict["name-2"]) 
print(dict)

print(dict.items())
print("------------------------")


# x = {1001:"A",1002:"B",1003:"C"}
# print(x)

# dict.update(x)
# print(dict)

x = {"A": 100 , "B" :200, "C":300}
# L =[]
# for i in x.values:
#     l.append(i.values)

# print(sum(l))

# print(x.values())
# print(sum(x.values()))

def wish(name):
    print("hi,hello:",name)

wish("krishna")
wish("lavanya")
def add(x,y):
    print(x+y)
    
add(10,20)
add("hi","hello")


def result(m,p,c,e,h):
    totalmarks = m+p+c+e+h
    print(totalmarks)
    print(totalmarks/tm*100)
m = 100
p = 80
c = 90
e = 100
h = 70
tm = 500
result(m,p,c,e,h)

def add(x,y):
    return(x+y)
sm = add(10,20)

if sm%2==0:
    print("is even")
else:
    print("not a even")

def add(x,y):
    return(x+y)
sm = add(10,20)

if sm %2==0:
    print("is even")
else:
    print("not a even")

def count_char(d):
    # l = len(d)
    d1 = {}
    for i in d:
        if i in d1:
            d1[i] = d1[i]+1
        else:
            d1[i]=1
            return d1
            
d = "skywavessoftware"
print(count_char(d))

def factorial(z):
    if z == 0:
        return 1
    else:
        return(z*factorial(z-1))
    
print( factorial(5))
print(5*4*3*2*1)

l = lambda x : x*x
print(l(5))
l = lambda x,y : x+y
print(l(10,20))
l = lambda x,y : x if x>y else y
print(l(500,800))

# filter(function,sequence)

# f = filter(get_even,l)

def get_evens(l):
    if l%2==0:
        return True
l = [1,2,3,4,5,6,7,8,9]
f = filter(get_evens,l)
print(list(f))

# l =[1,2,3,4,5,6,7,8,9]
# rs = reduce(lambda x,y:x+y+1)
# print(rs)
l =[1,2,3,4,5,6,7,8,9]
def sqr(l):
    return l*2
m = map(sqr,l)
print(list(m))

def add(x,y):
    print(x-y)

add(10,20)

def add(y,x):
    print(x-y)

add(10,20)

def add(x,y):
    print("x-",x)
    print("y-",y)
    print(x-y)
add(10,20)

def add(y,x):
    print("y-",y)
    print("x-",x)
    print(x-y)
add(10,20)
def greet (s1,s2):
    print(s1+s2)
greet("hbd","krishna")
def greet (s1,s2):
    print(s2+s1)
greet("hbd","krishna")

def wish(name,msg):
    print(msg+name)

wish("happy bday" ,"ram")

def add(x,y):
    print("x-",x)
    print("y-",y)
    print(x-y)

add(x=10, y = 20)

def add(y,x):
    print("y-",y)
    print("x-",x)
    print(y-x)

add(x = 10,y = 20)

def add(*l):
    total = 0
    for i in l:
        total = total+i
        return total
    
print(add(1,2,3,4,5,6,7,8,9))
print(add(20.38,40,70,88,89))


def marks(**l):
    for k,v in l.items():
        print(k,"-",v)
    print(sum(l.values()))

(marks(m = 30,p = 50,c = 40,e = 60,h = 90))

def data(email,firstname,lastname= None):
    print(email)
    print(firstname)
    print(lastname)

data("ram@gmail.com","ram")
data("krishna@gmail.com","krishna","hema")